// <auto-generated />
using System;
using IntelliDoc.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntelliDoc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntelliDoc.Domain.Entities.CampoExtraido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("text");

                    b.Property<bool>("CorrigidoManualmente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeCampo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ValorExtraidoIa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ValorFinal")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("IX_CamposExtraidos_DocumentoId");

                    b.ToTable("CamposExtraidos", (string)null);
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.ConfiguracaoEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LimiarConfiancaIa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(70.00m);

                    b.Property<bool>("SegregacaoRevisorAtiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TiposDocumentoAceitos")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique();

                    b.ToTable("ConfiguracoesEmpresa", (string)null);
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Arquivado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("text");

                    b.Property<string>("CaminhoArmazenamento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnviadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NomeArquivoOriginal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("PrioridadeRevisao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TentativasProcessamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<short>("TipoDocumento")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("EnviadoPorUsuarioId");

                    b.HasIndex("EmpresaId", "Status")
                        .HasDatabaseName("IX_Documentos_Empresa_Status");

                    b.HasIndex("EmpresaId", "PrioridadeRevisao", "Status")
                        .HasDatabaseName("IX_Documentos_Empresa_Prioridade_Status");

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("text");

                    b.Property<string>("CnpjOuIdentificador")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CnpjOuIdentificador")
                        .IsUnique();

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.HistoricoStatusDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<short>("StatusAnterior")
                        .HasColumnType("smallint");

                    b.Property<short>("StatusNovo")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId")
                        .HasDatabaseName("IX_HistoricoStatus_DocumentoId");

                    b.ToTable("HistoricoStatusDocumento", (string)null);
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text");

                    b.Property<Guid?>("DocumentoRelacionadoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Lida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<short?>("PapelDestino")
                        .HasColumnType("smallint");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UsuarioDestinoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioDestinoId", "Lida")
                        .HasDatabaseName("IX_Notificacoes_Usuario_Lida");

                    b.ToTable("Notificacoes", (string)null);
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "RevogadoEm");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Acao")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text");

                    b.Property<string>("DadosAntesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("DadosAntes");

                    b.Property<string>("DadosDepoisJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("DadosDepois");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("EnderecoIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("EntidadeAfetada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("EntidadeAfetadaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "CriadoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Auditoria_Empresa_CriadoEm");

                    b.ToTable("RegistrosAuditoria", (string)null);
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.UsuarioPapel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AtualizadoPor")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text");

                    b.Property<short>("Papel")
                        .HasColumnType("smallint");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Papel")
                        .IsUnique();

                    b.ToTable("UsuarioPapeis", (string)null);
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.CampoExtraido", b =>
                {
                    b.HasOne("IntelliDoc.Domain.Entities.Documento", null)
                        .WithMany("Campos")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("IntelliDoc.Domain.ValueObjects.ConfidenceScore", "Confidence", b1 =>
                        {
                            b1.Property<Guid>("CampoExtraidoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("ConfidenceScore");

                            b1.HasKey("CampoExtraidoId");

                            b1.ToTable("CamposExtraidos");

                            b1.WithOwner()
                                .HasForeignKey("CampoExtraidoId");
                        });

                    b.Navigation("Confidence")
                        .IsRequired();
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.ConfiguracaoEmpresa", b =>
                {
                    b.HasOne("IntelliDoc.Domain.Entities.Empresa", null)
                        .WithOne("Configuracao")
                        .HasForeignKey("IntelliDoc.Domain.Entities.ConfiguracaoEmpresa", "EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.Documento", b =>
                {
                    b.HasOne("IntelliDoc.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntelliDoc.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("EnviadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("IntelliDoc.Domain.ValueObjects.ConfidenceScore", "ScoreMedio", b1 =>
                        {
                            b1.Property<Guid>("DocumentoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("ConfidenceScoreMedio");

                            b1.HasKey("DocumentoId");

                            b1.ToTable("Documentos");

                            b1.WithOwner()
                                .HasForeignKey("DocumentoId");
                        });

                    b.Navigation("ScoreMedio");
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.HistoricoStatusDocumento", b =>
                {
                    b.HasOne("IntelliDoc.Domain.Entities.Documento", null)
                        .WithMany("Historico")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("IntelliDoc.Domain.Entities.Usuario", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("IntelliDoc.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("IntelliDoc.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.UsuarioPapel", b =>
                {
                    b.HasOne("IntelliDoc.Domain.Entities.Usuario", null)
                        .WithMany("Papeis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.Documento", b =>
                {
                    b.Navigation("Campos");

                    b.Navigation("Historico");
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Configuracao")
                        .IsRequired();
                });

            modelBuilder.Entity("IntelliDoc.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Papeis");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
